# Copyright 1999-@YEAR@ Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# File was automatically generated by automatic-ebuild-maker
# https://github.com/BlueManCZ/automatic-ebuild-maker

EAPI=@EAPI@
inherit @INHERIT@

DESCRIPTION="@DESCRIPTION@"
HOMEPAGE="@HOMEPAGE@"
SRC_URI="@SRC_URI@"

LICENSE="@LICENSE@"
SLOT="@SLOT@"
KEYWORDS="@KEYWORDS@"
RESTRICT="@RESTRICT@"
IUSE="@IUSE@"

RDEPEND="@RDEPEND@"

QA_PREBUILT="@QA_PREBUILT@"
